---
# tasks file for ansible-epel

- name: install epel repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm state=present
  become: yes
  when: ansible_os_family == "RedHat"

- name: install gpg key for epel
  rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }} state=present
  become: yes
  when: ansible_os_family == "RedHat"
